### ISSUE TITLE
Crash with Wurst and Wolfram

### ISSUE THREAD

**Issue by arnaudlanna** [Wurst-Imperium/WolframClient.net#9]
Everytime I open either Wurst client or Wolfram it crashes. I can open forge and the game with just optifine normaly.

3718 debugs7 infos3 warnings
15:11:10	launcher	main	info	Preparing to launch minecraft client for Wurst Client for Minecraft 1.11
15:11:11	launcher	main	warn	Couldn't get hash for Wurst Client for Minecraft 1.11 jar from https://s3.amazonaws.com/Minecraft.Download/versions/Wurst Client for Minecraft 1.11/Wurst Client for Minecraft 1.11.jar.sha1: HTTP 403: Forbidden
15:11:11	launcher	main	warn	Have local file C:/Users\Arnaud\AppData\Roaming\.minecraft\versions\Wurst Client for Minecraft 1.11/Wurst Client for Minecraft 1.11.jar but don't know what size or hash it should be. Have to assume it's good.
15:11:11	launcher	main	info	Checking installations.
15:11:11	launcher	main	info	Minecraft client Wurst Client for Minecraft 1.11 is ready to start.
15:11:11	launcher	main	info	Starting!
15:11:11	launcher	main	warn	Version does not support log configuration, will assume one plaintext entry per line
12:11:12	game		info	[15:11:12] [Client thread/INFO]: Setting user: KungPOWchan
12:11:13	game		info	[15:11:13] [Client thread/INFO]: LWJGL Version: 2.9.4
15:11:15	launcher	main	info	Process closed with exit code -1073740791

**Comment by arnaudlanna** [comment]
[02:48:09] [Client thread/INFO]: [STDERR]: java.io.FileNotFoundException: minecraft:wolfram/urwgothiclbook.ttf
[02:48:09] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.resources.FallbackResourceManager.getResource(FallbackResourceManager.java:75)
[02:48:09] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.resources.SimpleReloadableResourceManager.getResource(SimpleReloadableResourceManager.java:75)
[02:48:09] [Client thread/INFO]: [STDERR]: 	at net.wolframclient.Wolfram.getFont(Wolfram.java:167)
[02:48:09] [Client thread/INFO]: [STDERR]: 	at net.wolframclient.Wolfram.<clinit>(Wolfram.java:83)
[02:48:09] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.init(Minecraft.java:518)
[02:48:09] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.run(Minecraft.java:405)
[02:48:09] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:163)
[02:48:09] [Client thread/INFO]: [STDERR]: Font not loaded.  Using serif font.

The actual error before crashing is that on. Can you please help me?
